"""initial schema: users, profiles, reports, assumptions, runs

Revision ID: ab18e8d72ef4
Revises: 
Create Date: 2026-04-09 11:08:06.212863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab18e8d72ef4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_year', sa.String(length=16), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.String(length=10), nullable=True),
    sa.Column('effective_to', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_year')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=True),
    sa.Column('profile_path', sa.String(length=512), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('surplus_monthly', sa.Float(), nullable=True),
    sa.Column('net_worth', sa.Float(), nullable=True),
    sa.Column('debt_total', sa.Float(), nullable=True),
    sa.Column('savings_rate_pct', sa.Float(), nullable=True),
    sa.Column('pension_replacement_pct', sa.Float(), nullable=True),
    sa.Column('emergency_fund_months', sa.Float(), nullable=True),
    sa.Column('goals_on_track', sa.Integer(), nullable=True),
    sa.Column('goals_at_risk', sa.Integer(), nullable=True),
    sa.Column('goals_unreachable', sa.Integer(), nullable=True),
    sa.Column('high_interest_debt_count', sa.Integer(), nullable=True),
    sa.Column('mortgage_readiness', sa.String(length=32), nullable=True),
    sa.Column('full_report_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_profile_name'), 'runs', ['profile_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_profile_name')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('json_content', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_profile_id'), 'reports', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_profile_id'), table_name='reports')
    op.drop_index('ix_reports_generated_at', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_runs_profile_name'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('assumptions')
    # ### end Alembic commands ###
